#!/usr/bin/env python3
"""PMOS host-bundle generator (gstack defineHost() pattern, HOST-ADAPTER.md).

One declarative hosts/<host>.json per agent host (jcode = reference, claude,
hermes). The generator renders a host bundle under host-bundles/<host>/ with
every jcode-ism rewritten to the host's tool names and suppressed features
removed, so the protocol's instructions name the host's real tools:

    python tools/hostgen.py --host claude     # render one host
    python tools/hostgen.py --all             # render every host in hosts/
    python tools/hostgen.py --check           # CI: bundles fresh + rewrite coverage

A bundle is GENERATED. Edit hosts/<host>.json or the source docs, never the
bundle; --check fails when a bundle is stale, a rewrite source never appears
(dead entry), or a jcode-ism survives in a rendered bundle (missed entry).
"""
import argparse
import json
import re
import sys
from pathlib import Path

TPL = Path(__file__).resolve().parent.parent
HOSTS_DIR = TPL / "hosts"
OUT_DIR = TPL / "host-bundles"

# Source files that get rewritten into every bundle.
PROTOCOL_DOCS = [TPL / "ORCHESTRATOR.md"] + sorted(
    (TPL / "docs" / "stages").glob("*.md"))


def load_hosts():
    hosts = {}
    for p in sorted(HOSTS_DIR.glob("*.json")):
        cfg = json.loads(p.read_text(encoding="utf-8"))
        hosts[cfg["name"]] = cfg
    return hosts


def rewrite(text, cfg):
    for entry in cfg.get("tool_rewrites") or []:
        text = text.replace(entry["from"], entry["to"])
    return text


def drop_suppressed(text, cfg):
    for feat in cfg.get("suppressed") or []:
        # drop the methodology-upgrade sentence mentioning the suppressed feature
        if feat == "gstack":
            text = re.sub(r"\n5\. METHODOLOGY UPGRADE.*?\n(?=\d+\.)", "\n", text, flags=re.S)
    return text


def spawn_prompt(cfg):
    text = (TPL / "docs" / "stages" / "spawn-fallback.md").read_text(encoding="utf-8")
    blocks = re.findall(r"```\n(.*?)```", text, re.S)
    prompt = blocks[0] if blocks else ""
    prompt = drop_suppressed(prompt, cfg)
    return rewrite(prompt, cfg)


def agent_files(cfg):
    """Per-role agent definitions from roster.json (subagent format)."""
    roster = json.loads((TPL / "roster.json").read_text(encoding="utf-8"))
    files = {}
    for role, rdef in roster["roles"].items():
        skills = ", ".join(rdef.get("skills") or [])
        files["agents/%s.md" % role] = (
            "# %s\n\n"
            "Role: %s\n"
            "KB namespace: %s\n"
            "Skills: %s\n"
            "Artifacts: %s\n\n"
            "%s\n" % (rdef["name"], role, rdef.get("kb_namespace", role),
                      skills, "; ".join(rdef.get("artifacts") or []), rdef.get("when", "")))
    return files


def render_host(cfg):
    out = OUT_DIR / cfg["name"]
    (out / "agents").mkdir(parents=True, exist_ok=True)
    (out / "docs" / "stages").mkdir(parents=True, exist_ok=True)

    (out / "spawn-prompt.md").write_text(spawn_prompt(cfg), encoding="utf-8")
    for rel, body in agent_files(cfg).items():
        (out / rel).write_text(body, encoding="utf-8")

    # the entry-point skills, rewritten for this host (template root path,
    # swarm/tool references) so the bundle is self-contained
    for sp in sorted((TPL / "skills").glob("*/SKILL.md")):
        rel = sp.relative_to(TPL)
        text = sp.read_text(encoding="utf-8")
        text = rewrite(text, cfg)
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8")

    # do-not-touch as prevention (gstack G6) + verified-done enforcement
    # (L-12): hosts with file-scope hooks get a PreToolUse hook template that
    # denies edits outside the worker's touches set, and a Stop hook template
    # that runs artifacts.py --strict before the worker's "done" report lands.
    # The coordinator fills the paths per worker at spawn.
    hooks = cfg.get("file_scope_hooks") or {}
    if hooks.get("available"):
        (out / "hooks-pretool-edit.json").write_text(
            _pretool_hook_template(cfg), encoding="utf-8")
        (out / "hooks-stop-verify.json").write_text(
            _stop_verify_hook_template(cfg), encoding="utf-8")

    for src in PROTOCOL_DOCS:
        rel = src.relative_to(TPL)
        text = src.read_text(encoding="utf-8")
        text = drop_suppressed(text, cfg)
        text = rewrite(text, cfg)
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8")

    readme = TPL / "hosts" / ("%s.md" % cfg["name"])
    (out / "README.md").write_text(
        readme.read_text(encoding="utf-8") if readme.is_file()
        else "# %s bundle\n\nGenerated by tools/hostgen.py. See HOST-ADAPTER.md.\n" % cfg["display_name"],
        encoding="utf-8")
    return out


def _pretool_hook_template(cfg):
    """Claude Code PreToolUse hook that denies Edit/Write outside the worker's
    touches set (gstack /freeze mechanism). {{TOUCHES}} is filled by the
    coordinator at spawn from the task's touches field."""
    return json.dumps({
        "hooks": {
            "PreToolUse": [{
                "matcher": "Edit|Write",
                "hooks": [{
                    "type": "command",
                    "command": "python3 - <<'EOF'\nimport json, sys\ninp = json.load(sys.stdin)\np = inp[\"tool_input\"].get(\"file_path\", \"\")\ntouches = \"{{TOUCHES}}\".split(\",\")\nif touches and not any(p.startswith(t) for t in touches):\n    print(json.dumps({\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": \"outside touches set: %s\" % p}}))\nEOF"
                }]
            }]
        }
    }, indent=1) + "\n"


def _stop_verify_hook_template(cfg):
    """Claude Code Stop hook (L-12): run artifacts.py --strict before the
    worker's "done" report ends the turn, so a worker cannot report done with
    unresolved artifact errors — the gstack-verify-gate pattern. {{PROJ}} is
    filled by the coordinator at spawn."""
    return json.dumps({
        "hooks": {
            "Stop": [{
                "hooks": [{
                    "type": "command",
                    "command": "python3 %s --project {{PROJ}} --strict" % (TPL / "tools" / "artifacts.py")
                }]
            }]
        }
    }, indent=1) + "\n"


def check_host(cfg):
    """Freshness + rewrite coverage for one host. Returns list of problems."""
    problems = []
    out = OUT_DIR / cfg["name"]
    rendered = render_host(cfg)  # render fresh copy in memory (writes again; cheap)
    # freshness: rendered bytes must match what's on disk
    for p in sorted(rendered.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(out)
        disk = out / rel
        if not disk.is_file() or disk.read_bytes() != p.read_bytes():
            problems.append("stale: %s" % rel)
    # rewrite coverage: every 'from' must appear in the SOURCE docs/skills (not dead)
    src_text = "\n".join(p.read_text(encoding="utf-8") for p in PROTOCOL_DOCS)
    src_text += "\n" + "\n".join(
        p.read_text(encoding="utf-8") for p in (TPL / "skills").glob("*/SKILL.md"))
    for entry in cfg.get("tool_rewrites") or []:
        if entry["from"] not in src_text:
            problems.append("dead rewrite: %r" % entry["from"])
    # no jcode-ism survives in the rendered bundle (except the reference host)
    if cfg["name"] != "jcode":
        bundled = "\n".join(p.read_text(encoding="utf-8")
                            for p in rendered.rglob("*") if p.is_file())
        for bad in ["swarm", "jcode"]:
            if bad in bundled:
                problems.append("jcode-ism survived: %r" % bad)
    return problems


def main():
    ap = argparse.ArgumentParser(description="PMOS host-bundle generator")
    ap.add_argument("--host", default=None, help="render one host (name from hosts/*.json)")
    ap.add_argument("--all", action="store_true", help="render every host")
    ap.add_argument("--check", action="store_true",
                    help="verify bundles are fresh and rewrites cover the docs")
    args = ap.parse_args()

    hosts = load_hosts()
    if args.check:
        rc = 0
        for name, cfg in hosts.items():
            problems = check_host(cfg)
            if problems:
                rc = 1
                print("[FAIL] %s:" % name)
                for p in problems:
                    print("   - %s" % p)
            else:
                print("[OK]   %s" % name)
        print("HOSTGEN CHECK %s" % ("PASS" if rc == 0 else "FAILED"))
        return rc

    targets = hosts if args.all else (
        {args.host: hosts[args.host]} if args.host and args.host in hosts else {})
    if not targets:
        print("no host rendered (use --host <name> or --all); hosts: %s"
              % ", ".join(sorted(hosts)), file=sys.stderr)
        return 2
    for name in sorted(targets):
        render_host(hosts[name])
        print("rendered host-bundles/%s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
